name: app
description:
publish_to:

version: 1.0.0+2

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  card_swiper: ^3.0.1
  skeletons: ^0.0.3
  dio: ^5.4.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  get: ^4.6.6
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  intl: ^0.19.0
  share_plus: ^7.2.2
  multi_select_flutter:
  chat_bubbles: ^1.6.0
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  image_cropper: ^5.0.1
  flutter_stripe: ^11.0.0
  blur: ^3.1.0
  page_transition: ^2.1.0
  flutter_widget_from_html: ^0.15.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

